### ISSUE TITLE
Failed to connect to an active debugger client

### ISSUE THREAD

**Issue by algarih** [helsmy/autohotkey-debug-adaptor#11]
I have installed this extension and when I tried to start the debug i get this error:

"Failed to connect to an active debugger client"

**Comment by helsmy** [comment]
It may caused by name of the file. Non-ascii named files may crash the debugger due to something of stdio of ahk. Could you provide more information about it?

**Comment by helsmy** [comment]
Because of no feather information, this is closed

**Comment by Wielkimati** [comment]
Hey @helsmy, could this be reopened?
I'm also having this same issue, however, my file name (SlimepedeGrind.ahk2) doesn't contain any non-ASCII characters. 

Not sure what other info to provide, since the error only states what algarith already said. "Failed to connect to an active debugger client. Continue running the script without the debugger?" Is there maybe a log created anywhere that I could attach or anything?

**Comment by helsmy** [comment]
Yes, any time if there is same problem. Are there some way to reproduce it? "Failed to connect to an active debugger client." is produced by autohotkey itself when script started in debug mode and no debugger is connectted. Sometimes, restart scripts too fast will cause this error and launch script again will make everything working again.

**Comment by Wielkimati** [comment]
I don't know if this is caused in any way by the script itself, I can replicate this every time I try to use your extension to debug my script.

1. I had a clean install of VSCode
2. I downloaded first AutoHotkey v2 Language Support by thqby off the built-in extension browser - https://github.com/thqby/vscode-autohotkey2-lsp
3. I downloaded your extension, also off the built-in browser
4. Any scripts, even one with basic msgBox, can be started without issues using the first extension, directly from VSCode.
5. Whenever I select the option to debug the script (either F5 or via context menu), this error appears for me, and I can select if I want to continue without debugger or not.

Sorry if this seems a bit chaotic, I'm just really not sure what else I could provide to help with this issue, but I'm open to sharing whatever you need.

**Comment by helsmy** [comment]
Extension by thqby will give a custom setting to debugger if it doesn't find any launch.json. I don't know if the custom setting leads any problem. May you can try to start debug with your custom setting by setting up a launch.json.

How to create a launch.json:
1. Open a folder in vscode and in debug context menu click `the gear icon` vscode will create a launch.json and open it. 
2. In launch.json click the blue `Add configuration` button in right bottom.
3. A popup list menu will show up. Select the `Autohotkey Debug: Launch`.
4. change item `"AhkExecutable"` to you autohotkey interpreter path, then save the file.
5. In debug context menu, you can find `A new configuration for 'debugging' AutoHotKey.` in dropdown list menu, then select it and debug will launch with your custom setting

**Comment by Wielkimati** [comment]
Hey,

Yeah, this helped, it's working now. So it was an issue with configuration and lack of knowledge on my part. 

Thank you for your help and time, this can be closed now.
