### ISSUE TITLE
Can't debug script

### ISSUE THREAD

**Issue by F0x06** [helsmy/autohotkey-debug-adaptor#9]
Hi, i tried to debug a simple MsgBox script and i get this error:
````
MsgBox.ahk launch fail 'Jinvalid language.'Jextra:AHK'
````

Run without debugging works as expected.

AutoHotKey version: 1.1.33.11
VsCode version: 1.61.0

Any idea ? 

Thanks in advance.

**Comment by helsmy** [comment]
Because of recent update, extension only works with compiled script. 
Now, to bypass the checking of language id:
1. clone this project
2. in `ahkdbg\AHKRuntime.ahk` delete 92-100 lines
3. compile this extension as described in the readme
